# Generated by Django 5.2.10 on 2026-03-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mainnews_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='TrendingNews/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.CharField(max_length=200)),
            ],
        ),
    ]
