# Generated by Django 5.2.10 on 2026-03-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_videonews_remove_news_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ListNews/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
    ]
