# Generated by Django 5.2.10 on 2026-03-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_listnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingNewsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='TrendingNewsList/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
