# Generated by Django 5.2.10 on 2026-03-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_singlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepage',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
