# Generated by Django 5.2.10 on 2026-03-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_listnews_views_mainnews_views_mainnewsbig_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50000)),
                ('url_in', models.URLField()),
                ('url_google', models.URLField()),
                ('url_facebook', models.URLField()),
                ('url_twitter', models.URLField()),
            ],
        ),
    ]
