# Generated by Django 5.2.10 on 2026-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_member_event_forum_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingnews',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
