# Generated by Django 5.2.10 on 2026-03-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepage',
            name='is_about_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singlepage',
            name='is_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
