# Generated by Django 5.2.10 on 2026-03-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_singlepage_is_about_page_singlepage_is_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainnewsbig',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
    ]
