# Generated by Django 5.2.10 on 2026-04-01 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_mainnewsbig_is_breaking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='singlepage',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=432, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlepage',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='singlepage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='singlepage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post', to='app.category'),
        ),
        migrations.AlterField(
            model_name='trendingnewslist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.category'),
        ),
    ]
