# Generated by Django 5.2.10 on 2026-04-02 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_mainnews_status_news_status_singlepage_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True)),
                ('position', models.CharField(choices=[('home_top', 'Home Page Top'), ('home_sidebar', 'Home Page Sidebar'), ('article_top', 'Article Page Top'), ('article_sidebar', 'Article Page Sidebar'), ('footer', 'Footer'), ('popup', 'Popup')], default='home_top', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('bot_token', models.CharField(max_length=200)),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_username', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('post_format', models.TextField(blank=True, help_text='Use {title}, {category}, {description}, {link} as placeholders')),
                ('test_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Telegram Settings',
            },
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='created_at',
        ),
        migrations.CreateModel(
            name='TelegramLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('error', 'Error'), ('retry', 'Retry')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('telegram_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_logs', to='app.singlepage')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
