# Generated by Django 5.2.10 on 2026-04-02 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_banner_telegramsetting_remove_likedislike_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedislike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramsetting',
            name='post_format',
            field=models.TextField(blank=True),
        ),
    ]
