# Generated by Django 5.2.10 on 2026-04-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_likedislike_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20, unique=True)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('icon_class', models.CharField(blank=True, help_text='Font awesome icon class (e.g., fa-facebook)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Social Media Links',
            },
        ),
    ]
