from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap as django_sitemap

from .views import (index, contact, technology, business, register, login, events, forums, members, single,
                    science, groups, politics, blog, profile, logout_view, category_detail, search, subscribe_view,
                    verify_email, newsletter_subscribe, success_view, add_comment, toggle_bookmark, vote,
                    my_bookmarks, tag_detail, featured_news, breaking_news, about, author_detail, sitemap as app_sitemap, robots_txt,
                    comment_vote, delete_comment, telegram_test_send)

urlpatterns = [
    path('', index, name='home'),
    path('about/', about, name='about'),
    path('author/<int:user_id>/', author_detail, name='author_detail'),
    path('subscribe/', subscribe_view, name='subscribe'),
    path('newsletter-subscribe/', newsletter_subscribe, name='newsletter_subscribe'),
    path('verify-email/', verify_email, name='verify_email_page'),
    path('verification-success/', success_view, name='success_page'),
    path('contact/', contact, name='contact'),
    path('technology/', technology, name='technology'),
    path('business/', business, name='business'),
    path('events/', events, name='events'),
    path('forums/', forums, name='forums'),
    path('members/', members, name='members'),
    path('single/<int:id>/', single, name='single'),
    path('science/', science, name='science'),
    path('groups/', groups, name='groups'),
    path('politics/', politics, name='politics'),
    path('blog/',blog, name='blog'),
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('profile/', profile, name='profile'),
    path('logout/', logout_view, name='logout'),
    path('search/', search, name='search'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), name='password_change_done'),
    path('category/<slug:slug>/', category_detail, name='category_detail'),
    path('comment/add/', add_comment, name='add_comment'),
    path('bookmark/toggle/', toggle_bookmark, name='toggle_bookmark'),
    path('bookmarks/', my_bookmarks, name='my_bookmarks'),
    path('vote/', vote, name='vote'),
    path('tag/<slug:slug>/', tag_detail, name='tag_detail'),
    path('featured/', featured_news, name='featured_news'),
    path('breaking/', breaking_news, name='breaking_news'),
    path('sitemap.xml', app_sitemap, name='sitemap'),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('comment/vote/', comment_vote, name='comment_vote'),
    path('comment/delete/', delete_comment, name='delete_comment'),
    path('telegram/test-send/', telegram_test_send, name='telegram_test_send'),
]